/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_HelloJNI */

#ifndef _Included_pkg_HelloJNI
#define _Included_pkg_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkg_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pkg_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     pkg_HelloJNI
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_pkg_HelloJNI_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     pkg_HelloJNI
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pkg_HelloJNI_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     pkg_HelloJNI
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lpkg/UserData;
 */
JNIEXPORT jobject JNICALL Java_pkg_HelloJNI_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     pkg_HelloJNI
 * Method:    printUserData
 * Signature: (Lpkg/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pkg_HelloJNI_printUserData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     pkg_HelloJNI
 * Method:    search
 * Signature: ([[DI)[[[D
 */
JNIEXPORT jobjectArray JNICALL Java_pkg_HelloJNI_search
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
